
spring.application.name=TaskAutomation

# Database configuration (Aiven MySQL)
spring.datasource.url=jdbc:mysql://mysql-task-automation-task-automation-db.f.aivencloud.com:14862/deadline?useSSL=true&serverTimezone=UTC
spring.datasource.username=
    
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Authentication
app.jwtSecret=${JWT_SECRET:TaskAutomationSuperSecretKeyForJwtSigning1234567890!@#$}
app.jwtExpirationMs=86400000

# SQL Initialization (for data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# URL Webhook của n8n trên VPS (ví dụ: https://n8nserver.email/webhook/task-created)
n8n.webhook.url=https://n8nserver.email/webhook/task-created


